--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JustTalDevelops/iHateHive
build-by-default: true
branches:
- master
projects:
  HiveCorruptor:
    path: ""
    icon: "hive.png"
...
